# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('relationship', models.CharField(choices=[('mother', 'Mãe'), ('father', 'Pai'), ('guardian', 'Tutor'), ('other', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Ocupação')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Alternativo')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Comercial')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='schools.school', verbose_name='Escola')),
                ('students', models.ManyToManyField(related_name='guardians', to='students.student', verbose_name='Alunos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'indexes': [models.Index(fields=['school', 'is_active'], name='guardians_g_school__5dc43e_idx'), models.Index(fields=['cpf'], name='guardians_g_cpf_7f662f_idx')],
            },
        ),
    ]
