# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Série/Nível')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='schools.school', verbose_name='Escola')),
                ('subjects', models.ManyToManyField(related_name='curriculums', to='subjects.subject', verbose_name='Disciplinas')),
            ],
            options={
                'verbose_name': 'Grade Curricular',
                'verbose_name_plural': 'Grades Curriculares',
                'unique_together': {('school', 'grade_level', 'year')},
            },
        ),
    ]
