# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('education_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_matrices', to='governance.educationdepartment', verbose_name='Secretaria')),
                ('education_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_matrices', to='governance.educationstage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('bncc_code', models.CharField(blank=True, max_length=50, verbose_name='Código BNCC')),
                ('area_of_knowledge', models.CharField(max_length=100, verbose_name='Área do Conhecimento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('minimum_passing_grade', models.DecimalField(decimal_places=2, default=6.0, max_digits=4, verbose_name='Nota Mínima')),
                ('education_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='governance.educationdepartment', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='CurriculumMatrixItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('weekly_hours', models.PositiveIntegerField(verbose_name='Horas semanais')),
                ('annual_hours', models.PositiveIntegerField(verbose_name='Horas anuais')),
                ('curriculum_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curriculum.curriculummatrix', verbose_name='Matriz')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_items', to='curriculum.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Item da Matriz Curricular',
                'verbose_name_plural': 'Itens da Matriz Curricular',
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['education_department', 'is_active'], name='curriculum__educati_3d1f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('education_department', 'name'), name='uq_subject_dept_name'),
        ),
        migrations.AddConstraint(
            model_name='curriculummatrixitem',
            constraint=models.UniqueConstraint(fields=('curriculum_matrix', 'subject'), name='uq_matrix_subject'),
        ),
    ]
