# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('justified', 'Justificado'), ('excused', 'Permitido')], max_length=20, verbose_name='Status')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.class', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='subjects.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'indexes': [models.Index(fields=['student', 'class_obj', 'date'], name='attendance__student_c09a0c_idx'), models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx')],
                'unique_together': {('student', 'class_obj', 'subject', 'date')},
            },
        ),
    ]
