# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Formação Acadêmica')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Especialização')),
                ('hiring_date', models.DateField(auto_now_add=True, verbose_name='Data de Contratação')),
                ('employment_status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('on_leave', 'De Licença')], default='active', max_length=20, verbose_name='Status')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school', verbose_name='Escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'indexes': [models.Index(fields=['school', 'employment_status'], name='teachers_te_school__280efc_idx'), models.Index(fields=['cpf'], name='teachers_te_cpf_c39041_idx')],
            },
        ),
    ]
