# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Número da Carteirinha')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('expiration_date', models.DateField(verbose_name='Data de Validade')),
                ('qr_code', models.ImageField(upload_to='qr_codes/', verbose_name='QR Code')),
                ('qr_code_data', models.TextField(verbose_name='Dados QR Code')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_card', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Carteirinha',
                'verbose_name_plural': 'Carteirinhas',
            },
        ),
    ]
