# Generated by Django 6.0.7 on 2026-07-09 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('address_number', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de Fundação')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Diretor')),
                ('secretary_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Secretaria')),
                ('max_students_per_class', models.IntegerField(default=40, verbose_name='Máximo de Alunos por Turma')),
                ('school_year_start', models.IntegerField(default=1, verbose_name='Início do Ano Letivo (mês)')),
                ('school_year_end', models.IntegerField(default=12, verbose_name='Fim do Ano Letivo (mês)')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'indexes': [models.Index(fields=['cnpj'], name='schools_sch_cnpj_5c0ea9_idx'), models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'), models.Index(fields=['is_active'], name='schools_sch_is_acti_522730_idx')],
            },
        ),
    ]
