# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('inep_code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código INEP')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('school_type', models.CharField(choices=[('CRECHE', 'Creche'), ('PRE_ESCOLA', 'Pré-escola'), ('FUNDAMENTAL_1', 'Fundamental I'), ('FUNDAMENTAL_2', 'Fundamental II'), ('EJA', 'EJA'), ('MISTA', 'Mista')], max_length=50, verbose_name='Tipo de Escola')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('address_zip_code', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('max_students_per_class', models.IntegerField(default=30, verbose_name='Máximo de Alunos por Turma')),
                ('director_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_schools', to=settings.AUTH_USER_MODEL, verbose_name='Diretor')),
                ('education_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='governance.educationdepartment', verbose_name='Secretaria Municipal')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'indexes': [models.Index(fields=['education_department'], name='schools_sch_educati_8040ac_idx'), models.Index(fields=['inep_code'], name='schools_sch_inep_co_fc1cdb_idx'), models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'), models.Index(fields=['is_active'], name='schools_sch_is_acti_522730_idx')],
            },
        ),
    ]
