# Generated by Django 6.1 on 2026-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Rota do evento"
            ),
        ),
    ]
