# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('widget_type', models.CharField(max_length=100, verbose_name='Tipo de Widget')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('position', models.IntegerField(verbose_name='Posição')),
                ('settings', models.JSONField(default=dict, verbose_name='Configurações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Widget do Dashboard',
                'verbose_name_plural': 'Widgets do Dashboard',
            },
        ),
    ]
