# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('number', models.CharField(max_length=20, verbose_name='Número/Identificação')),
                ('capacity', models.IntegerField(verbose_name='Capacidade')),
                ('floor', models.IntegerField(verbose_name='Andar')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Bloco/Prédio')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Tem Projetor')),
                ('has_whiteboard', models.BooleanField(default=True, verbose_name='Tem Quadro Branco')),
                ('has_blackboard', models.BooleanField(default=False, verbose_name='Tem Quadro Negro')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Tem Ar Condicionado')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Tem WiFi')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Sala de Aula',
                'verbose_name_plural': 'Salas de Aula',
                'indexes': [models.Index(fields=['school', 'is_active'], name='classrooms__school__5c2fec_idx')],
                'unique_together': {('school', 'number')},
            },
        ),
    ]
