# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('municipality_name', models.CharField(max_length=150, verbose_name='Município')),
                ('ibge_code', models.CharField(max_length=7, unique=True, verbose_name='Código IBGE')),
                ('secretary_name', models.CharField(blank=True, max_length=150, verbose_name='Secretário(a)')),
                ('min_passing_grade', models.DecimalField(decimal_places=2, default=6.0, max_digits=4, verbose_name='Nota mínima para aprovação')),
                ('min_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='Frequência mínima (%)')),
            ],
            options={
                'verbose_name': 'Secretaria Municipal de Educação',
                'verbose_name_plural': 'Secretarias Municipais de Educação',
                'ordering': ['municipality_name'],
            },
        ),
        migrations.CreateModel(
            name='EducationStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('stage_type', models.CharField(choices=[('INFANTIL', 'Educação Infantil'), ('FUNDAMENTAL_I', 'Fundamental — Anos Iniciais'), ('FUNDAMENTAL_II', 'Fundamental — Anos Finais'), ('EJA', 'EJA')], max_length=50, verbose_name='Tipo')),
                ('evaluation_type', models.CharField(choices=[('NUMERIC', 'Numérica'), ('CONCEPT', 'Conceito'), ('DESCRIPTIVE', 'Descritiva')], max_length=30, verbose_name='Tipo de Avaliação')),
            ],
            options={
                'verbose_name': 'Etapa de Ensino',
                'verbose_name_plural': 'Etapas de Ensino',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('ACTIVE', 'Ativo'), ('CLOSED', 'Encerrado')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Fim')),
                ('education_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_years', to='governance.educationdepartment', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('period_number', models.PositiveSmallIntegerField(verbose_name='Número do período')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Fim')),
                ('grade_deadline', models.DateField(verbose_name='Prazo de lançamento de notas')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='governance.academicyear', verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'Período Letivo',
                'verbose_name_plural': 'Períodos Letivos',
                'ordering': ['academic_year', 'period_number'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'period_number'), name='uq_academic_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('education_department', 'year'), name='uq_academic_year_dept'),
        ),
    ]
