# Generated by Django 6.1 on 2026-08-30 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
        ("students", "0002_transferrequest_target_enrollment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            (
                                "MATRICULA_USO_DADOS",
                                "Uso de dados pessoais para matrícula e gestão escolar",
                            ),
                            ("USO_IMAGEM", "Uso de imagem em materiais institucionais"),
                            (
                                "COMUNICACAO",
                                "Comunicações da rede por e-mail e telefone",
                            ),
                        ],
                        max_length=32,
                        verbose_name="Tipo de consentimento",
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(default=True, verbose_name="Concedido"),
                ),
                (
                    "term_version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versão do termo"
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado em"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de origem"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="students.student",
                        verbose_name="Aluno titular",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que registrou",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de consentimento",
                "verbose_name_plural": "Registros de consentimento",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "consent_type"],
                        name="governance__student_4f2704_idx",
                    )
                ],
            },
        ),
    ]
