# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('content', models.TextField(verbose_name='Conteúdo Ministrado')),
                ('homework', models.TextField(blank=True, verbose_name='Tarefa de Casa')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='classes.class', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='subjects.subject', verbose_name='Disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='teachers.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Diário de Classe',
                'verbose_name_plural': 'Diários de Classe',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['class_obj', 'date'], name='diary_diary_class_o_2af968_idx')],
            },
        ),
    ]
