# Generated by Django 6.1 on 2026-08-30 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status_code",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="User-Agent"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=64, verbose_name="Ação"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict, verbose_name="Detalhes"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Recurso"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID do objeto"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="audit_audit_action_766c6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "created_at"],
                name="audit_audit_model_n_e7cd6b_idx",
            ),
        ),
    ]
