# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total_classes', models.IntegerField(default=0, verbose_name='Total de Aulas')),
                ('absences', models.IntegerField(default=0, verbose_name='Faltas')),
                ('attendance_percentage', models.FloatField(default=100, verbose_name='% Presença')),
                ('overall_average', models.FloatField(blank=True, null=True, verbose_name='Média Geral')),
                ('final_status', models.CharField(choices=[('approved', 'Aprovado'), ('failed', 'Reprovado'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status Final')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_history', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
            },
        ),
    ]
