# Generated by Django 6.1 on 2026-08-30 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "secret",
                    models.CharField(
                        help_text="Secret TOTP base32 criptografado com Fernet",
                        max_length=255,
                        verbose_name="Segredo criptografado",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="True após a verificação bem-sucedida do primeiro código",
                        verbose_name="Confirmado",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmado em"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo 2FA (TOTP)",
                "verbose_name_plural": "Dispositivos 2FA (TOTP)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "code",
                    models.CharField(
                        help_text="SHA-256 do código de backup",
                        max_length=64,
                        verbose_name="Hash do código",
                    ),
                ),
                ("used", models.BooleanField(default=False, verbose_name="Usado")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Usado em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de backup 2FA",
                "verbose_name_plural": "Códigos de backup 2FA",
                "ordering": ["used", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "used"], name="authenticat_user_id_5af97b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "code"), name="uq_backup_code_per_user"
                    )
                ],
            },
        ),
    ]
