# Generated by Django 6.1 on 2026-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_totp_2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expira em"),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Enviado em"
            ),
        ),
    ]
