# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('workload', models.IntegerField(default=60, verbose_name='Carga Horária (horas)')),
                ('requires_practicum', models.BooleanField(default=False, verbose_name='Requer Prática')),
                ('minimum_passing_grade', models.FloatField(default=6.0, verbose_name='Nota Mínima')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'indexes': [models.Index(fields=['school', 'is_active'], name='subjects_su_school__5f3a22_idx')],
                'unique_together': {('school', 'code')},
            },
        ),
    ]
