# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('year', models.IntegerField(verbose_name='Ano Letivo')),
                ('semester', models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], verbose_name='Semestre')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Série/Nível')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa'), ('archived', 'Arquivada')], default='active', max_length=20, verbose_name='Status')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classrooms.classroom', verbose_name='Sala de Aula')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='Escola')),
                ('subjects', models.ManyToManyField(related_name='classes', to='subjects.subject', verbose_name='Disciplinas')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='teachers.teacher', verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'indexes': [models.Index(fields=['school', 'year', 'status'], name='classes_cla_school__e40131_idx')],
                'unique_together': {('school', 'code', 'year', 'semester')},
            },
        ),
    ]
