# Generated by Django 6.1 on 2026-08-28 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('number', models.CharField(max_length=20, verbose_name='Número/Identificação')),
                ('capacity', models.IntegerField(verbose_name='Capacidade')),
                ('floor', models.IntegerField(verbose_name='Andar')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Bloco/Prédio')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Tem Projetor')),
                ('has_whiteboard', models.BooleanField(default=True, verbose_name='Tem Quadro Branco')),
                ('has_blackboard', models.BooleanField(default=False, verbose_name='Tem Quadro Negro')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Tem Ar Condicionado')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Tem WiFi')),
            ],
            options={
                'verbose_name': 'Sala de Aula',
                'verbose_name_plural': 'Salas de Aula',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('shift', models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('FULL_TIME', 'Integral'), ('NIGHT', 'Noite')], max_length=20, verbose_name='Turno')),
                ('max_capacity', models.PositiveIntegerField(default=30, verbose_name='Capacidade máxima')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Sala')),
                ('inep_class_code', models.CharField(blank=True, max_length=20, verbose_name='Código INEP da turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_regent', models.BooleanField(default=False, verbose_name='Regente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Alocação Docente',
                'verbose_name_plural': 'Alocações Docentes',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Matrícula funcional')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('formation_area', models.CharField(blank=True, max_length=150, verbose_name='Área de formação')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('hiring_date', models.DateField(blank=True, null=True, verbose_name='Data de Contratação')),
            ],
            options={
                'verbose_name': 'Perfil Docente',
                'verbose_name_plural': 'Perfis Docentes',
            },
        ),
    ]
