# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('governance', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='schools.school', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='governance.academicyear', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_classes', to='classes.classroom', verbose_name='Sala de Aula'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='curriculum_matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='curriculum.curriculummatrix', verbose_name='Matriz Curricular'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_classes', to='schools.school', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='classes.schoolclass', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='curriculum.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='governance.educationdepartment', verbose_name='Secretaria'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='classes.teacherprofile', verbose_name='Professor'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school', 'is_active'], name='classes_cla_school__314b7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'number')},
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'academic_year'], name='classes_sch_school__40dd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'is_active'], name='classes_sch_school__51ef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['education_department', 'is_active'], name='classes_tea_educati_68f5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['cpf'], name='classes_tea_cpf_ed8424_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherallocation',
            constraint=models.UniqueConstraint(fields=('teacher_profile', 'school_class', 'subject'), name='uq_allocation'),
        ),
    ]
