# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('integration_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('config', models.JSONField(default=dict, verbose_name='Configuração')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='schools.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
            },
        ),
    ]
