# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('document_type', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('birth_certificate', 'Certidão de Nascimento'), ('address_proof', 'Comprovante de Endereço'), ('previous_school', 'Histórico Anterior'), ('medical_report', 'Relatório Médico'), ('other', 'Outro')], max_length=50, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Arquivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Aluno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='documents_d_student_b0396b_idx')],
            },
        ),
    ]
