# Generated by Django 6.1 on 2026-08-28 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('backup_file', models.FileField(upload_to='backups/%Y/%m/', verbose_name='Arquivo de Backup')),
                ('backup_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(default='completed', max_length=20, verbose_name='Status')),
                ('size_mb', models.FloatField(verbose_name='Tamanho (MB)')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
