# Generated by Django 6.1 on 2026-08-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_initial"),
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="checksum",
            field=models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
        ),
        migrations.AddField(
            model_name="backup",
            name="error_log",
            field=models.TextField(blank=True, verbose_name="Log de erro"),
        ),
        migrations.AddField(
            model_name="backup",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backup",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backups_requested",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitado por",
            ),
        ),
        migrations.AddField(
            model_name="backup",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backup",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("automated", "Automático (agendado)"),
                    ("manual", "Manual (sob demanda)"),
                ],
                default="automated",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="backup_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="backups/%Y/%m/",
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="backup_type",
            field=models.CharField(
                default="database", max_length=50, verbose_name="Tipo"
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backups",
                to="schools.school",
                verbose_name="Escola",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="size_mb",
            field=models.FloatField(default=0, verbose_name="Tamanho (MB)"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Em execução"),
                    ("COMPLETED", "Concluído"),
                    ("FAILED", "Falhou"),
                ],
                default="RUNNING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="backup",
            index=models.Index(
                fields=["status", "created_at"], name="backups_bac_status_9e403b_idx"
            ),
        ),
    ]
