# Generated by Django 6.1 on 2026-08-28 13:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('EXCUSED_ABSENCE', 'Falta justificada')], max_length=20, verbose_name='Status')),
                ('justification_note', models.TextField(blank=True, verbose_name='Justificativa')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
        migrations.CreateModel(
            name='DescriptiveEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('development_report', models.TextField(verbose_name='Relatório de desenvolvimento')),
                ('learning_milestones', models.JSONField(blank=True, default=dict, verbose_name='Habilidades BNCC')),
            ],
            options={
                'verbose_name': 'Parecer Descritivo',
                'verbose_name_plural': 'Pareceres Descritivos',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('content', models.TextField(verbose_name='Conteúdo Ministrado')),
                ('homework', models.TextField(blank=True, verbose_name='Tarefa de Casa')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Diário de Classe',
                'verbose_name_plural': 'Diários de Classe',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('recovery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota de recuperação')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota final')),
                ('assessment_type', models.CharField(default='PERIOD_EXAM', max_length=50, verbose_name='Tipo de avaliação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='SchoolHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total_classes', models.IntegerField(default=0, verbose_name='Total de Aulas')),
                ('absences', models.IntegerField(default=0, verbose_name='Faltas')),
                ('attendance_percentage', models.FloatField(default=100, verbose_name='% Presença')),
                ('overall_average', models.FloatField(blank=True, null=True, verbose_name='Média Geral')),
                ('final_status', models.CharField(choices=[('approved', 'Aprovado'), ('failed', 'Reprovado'), ('pending', 'Pendente')], default='pending', max_length=20, verbose_name='Status Final')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
            },
        ),
    ]
