# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_diary', '0001_initial'),
        ('classes', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('governance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.schoolclass', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='curriculum.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='descriptiveevaluation',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptive_evaluations', to='governance.academicperiod', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='descriptiveevaluation',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_evaluations', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='descriptiveevaluation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptive_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='classes.schoolclass', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='curriculum.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_entries', to='classes.teacherprofile', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='governance.academicperiod', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.enrollment', verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='curriculum.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_launched', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='schoolhistory',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_history', to='students.student', verbose_name='Aluno'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date'], name='class_diary_enrollm_6c0aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='class_diary_date_bf3651_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date', 'subject'), name='uq_attendance_entry'),
        ),
        migrations.AddConstraint(
            model_name='descriptiveevaluation',
            constraint=models.UniqueConstraint(fields=('enrollment', 'academic_period'), name='uq_descriptive_entry'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['school_class', 'date'], name='class_diary_school__b46164_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['enrollment', 'subject'], name='class_diary_enrollm_5e2687_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject', 'academic_period'), name='uq_grade_entry'),
        ),
    ]
