# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidade')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='Local de Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('birth_certificate', models.CharField(blank=True, max_length=50, verbose_name='Certidão de Nascimento')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('transferred', 'Transferido'), ('dropped', 'Desistente')], default='active', max_length=20, verbose_name='Status')),
                ('needs_special_attention', models.BooleanField(default=False, verbose_name='Necessita Atenção Especial')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school', verbose_name='Escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'indexes': [models.Index(fields=['school', 'status'], name='students_st_school__332118_idx'), models.Index(fields=['registration_number'], name='students_st_registr_23d894_idx'), models.Index(fields=['cpf'], name='students_st_cpf_eeb4b2_idx')],
                'unique_together': {('school', 'registration_number')},
            },
        ),
    ]
