# Generated by Django 6.1 on 2026-08-28 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('governance', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Ocupação')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('unique_municipal_id', models.CharField(max_length=20, unique=True, verbose_name='Identificador municipal único')),
                ('inep_id', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ID INEP')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('social_name', models.CharField(blank=True, max_length=200, verbose_name='Nome social')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('birth_certificate', models.CharField(blank=True, max_length=50, verbose_name='Certidão de Nascimento')),
                ('nis_code', models.CharField(blank=True, max_length=15, verbose_name='NIS')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, verbose_name='Gênero')),
                ('race_color', models.CharField(blank=True, max_length=30, verbose_name='Raça/Cor')),
                ('mother_name', models.CharField(max_length=200, verbose_name='Nome da mãe')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do pai')),
                ('has_special_needs', models.BooleanField(default=False, verbose_name='Necessidades especiais')),
                ('special_needs_details', models.TextField(blank=True, verbose_name='Detalhes NEE')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('education_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='governance.educationdepartment', verbose_name='Secretaria')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (login opcional)')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('enrollment_number', models.CharField(max_length=50, unique=True, verbose_name='Número da matrícula')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('ENROLLED', 'Matriculado'), ('APPROVED', 'Aprovado'), ('FAILED_ACADEMIC', 'Reprovado por nota'), ('FAILED_ATTENDANCE', 'Reprovado por frequência'), ('TRANSFERRED_INTERNAL', 'Transferido (interno)'), ('TRANSFERRED_EXTERNAL', 'Transferido (externo)'), ('DROPOUT', 'Desistente'), ('DECEASED', 'Falecido')], default='ENROLLED', max_length=30, verbose_name='Status')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='governance.academicyear', verbose_name='Ano Letivo')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.schoolclass', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kinship_type', models.CharField(choices=[('MOTHER', 'Mãe'), ('FATHER', 'Pai'), ('LEGAL_GUARDIAN', 'Responsável legal'), ('GRANDPARENT', 'Avô/Avó'), ('OTHER', 'Outro')], max_length=50, verbose_name='Parentesco')),
                ('is_emergency_contact', models.BooleanField(default=True, verbose_name='Contato de emergência')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.guardian', verbose_name='Responsável')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Vínculo Aluno-Responsável',
                'verbose_name_plural': 'Vínculos Aluno-Responsável',
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('PENDING_SME', 'Pendente SME'), ('APPROVED_BY_SME', 'Aprovada pela SME'), ('ACCEPTED_BY_DESTINATION', 'Aceita pelo destino'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelada')], default='PENDING_SME', max_length=30, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='governance.academicyear', verbose_name='Ano Letivo')),
                ('destination_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='schools.school', verbose_name='Escola de destino')),
                ('origin_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='schools.school', verbose_name='Escola de origem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Solicitação de Transferência',
                'verbose_name_plural': 'Solicitações de Transferência',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['cpf'], name='students_gu_cpf_46b741_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['is_active'], name='students_gu_is_acti_b2eec2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['education_department', 'is_active'], name='students_st_educati_432bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['unique_municipal_id'], name='students_st_unique__e42ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cpf'], name='students_st_cpf_eeb4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['inep_id'], name='students_st_inep_id_f61518_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='students_st_full_na_6ea9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mother_name'], name='students_st_mother__f9788a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'school_class'], name='students_en_student_5ae4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='students_en_student_c1d60c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school_class', 'status'], name='students_en_school__d6123b_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ENROLLED')), fields=('student', 'academic_year'), name='uniq_active_enrollment_per_year'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='uq_student_guardian'),
        ),
    ]
