# Generated by Django 6.1 on 2026-08-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferrequest",
            name="target_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originating_transfer",
                to="students.enrollment",
                verbose_name="Matrícula de destino",
            ),
        ),
    ]
