# Generated by Django 6.1 on 2026-08-31 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_cpf_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianLinkCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=64, verbose_name="Hash do código"),
                ),
                (
                    "kinship_hint",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOTHER", "Mãe"),
                            ("FATHER", "Pai"),
                            ("LEGAL_GUARDIAN", "Responsável legal"),
                            ("GRANDPARENT", "Avô/Avó"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Parentesco sugerido",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                ("used", models.BooleanField(default=False, verbose_name="Utilizado")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resgatado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Vinculação",
                "verbose_name_plural": "Códigos de Vinculação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Confirmado em"
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_guardian_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Confirmado por",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="rejection_note",
            field=models.TextField(blank=True, verbose_name="Motivo da recusa"),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_guardian_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitado por",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Aguardando confirmação da escola"),
                    ("CONFIRMED", "Confirmado"),
                    ("REJECTED", "Recusado"),
                ],
                default="CONFIRMED",
                max_length=15,
                verbose_name="Situação",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("STAFF_CREATED", "Criado pela equipe"),
                    (
                        "SCHOOL_APPROVAL",
                        "Solicitado pelo responsável, aprovado pela escola",
                    ),
                    ("LINK_CODE", "Confirmado por código de vinculação"),
                ],
                default="STAFF_CREATED",
                max_length=20,
                verbose_name="Forma de verificação",
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(fields=["status"], name="students_st_status_dc9e53_idx"),
        ),
        migrations.AddField(
            model_name="guardianlinkcode",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_link_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gerado por",
            ),
        ),
        migrations.AddField(
            model_name="guardianlinkcode",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_codes",
                to="students.student",
                verbose_name="Aluno",
            ),
        ),
        migrations.AddField(
            model_name="guardianlinkcode",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_link_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Resgatado por",
            ),
        ),
        migrations.AddIndex(
            model_name="guardianlinkcode",
            index=models.Index(
                fields=["code_hash", "used"], name="students_gu_code_ha_a5a4e3_idx"
            ),
        ),
    ]
