# Generated by Django 6.1 on 2026-08-30 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('governance', '0001_initial'),
        ('reports', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_key', models.CharField(max_length=64, verbose_name='Relatório')),
                ('scope_level', models.CharField(max_length=16, verbose_name='Escopo')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros')),
                ('output_format', models.CharField(max_length=8, verbose_name='Formato')),
                ('contains_personal_data', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Na fila'), ('PROCESSING', 'Processando'), ('DONE', 'Concluído'), ('ERROR', 'Erro')], default='QUEUED', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_executions', to='classes.schoolclass')),
                ('education_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_executions', to='governance.educationdepartment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_executions', to='schools.school')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatório',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'created_at'], name='reports_rep_request_07823e_idx'), models.Index(fields=['status'], name='reports_rep_status_4a91b0_idx'), models.Index(fields=['report_key', 'created_at'], name='reports_rep_report__1ca787_idx')],
            },
        ),
    ]
