# Generated by Django 6.1 on 2026-08-28 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Mensagem')),
                ('read', models.BooleanField(default=False, verbose_name='Lido')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
            },
        ),
    ]
