# Generated by Django 6.1 on 2026-08-31 16:21

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("governance", "0002_consentrecord"),
        ("schools", "0002_school_latitude_school_longitude"),
        ("students", "0005_student_cpf_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "renewal_opens_at",
                    models.DateTimeField(verbose_name="Rematrícula abre em"),
                ),
                (
                    "renewal_closes_at",
                    models.DateTimeField(verbose_name="Rematrícula fecha em"),
                ),
                (
                    "new_request_opens_at",
                    models.DateTimeField(verbose_name="Novas matrículas abrem em"),
                ),
                (
                    "new_request_closes_at",
                    models.DateTimeField(verbose_name="Novas matrículas fecham em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("RENEWAL_OPEN", "Rematrícula aberta"),
                            ("RENEWAL_CLOSED", "Rematrícula encerrada"),
                            ("NEW_OPEN", "Novas matrículas abertas"),
                            ("NEW_CLOSED", "Novas matrículas encerradas"),
                            ("PROCESSED", "Alocação processada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "education_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_cycles",
                        to="governance.educationdepartment",
                        verbose_name="Secretaria",
                    ),
                ),
                (
                    "target_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_cycles",
                        to="governance.academicyear",
                        verbose_name="Ano letivo de destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo de Admissão",
                "verbose_name_plural": "Ciclos de Admissão",
                "ordering": ["-target_academic_year__year"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("NEW", "Novo entrante"),
                            ("RENEWAL_TRANSFER", "Transferência interna (rematrícula)"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do candidato"
                    ),
                ),
                (
                    "applicant_cpf",
                    core.fields.CPFField(
                        blank=True, null=True, verbose_name="CPF do candidato"
                    ),
                ),
                (
                    "applicant_birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "applicant_mother_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome da mãe"
                    ),
                ),
                (
                    "desired_shift",
                    models.CharField(max_length=20, verbose_name="Turno desejado"),
                ),
                (
                    "target_grade_label",
                    models.CharField(max_length=80, verbose_name="Série pretendida"),
                ),
                (
                    "residential_address",
                    models.CharField(
                        max_length=255, verbose_name="Endereço residencial"
                    ),
                ),
                (
                    "residential_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "residential_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SUBMITTED", "Enviada"),
                            ("AWAITING_PROCESSING", "Aguardando processamento"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="DRAFT",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviada em"
                    ),
                ),
                (
                    "score_total",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Pontuação"
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Detalhe da pontuação"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_requests",
                        to="admissions.admissioncycle",
                        verbose_name="Ciclo",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_requests",
                        to="students.guardian",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "lgpd_consent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_requests",
                        to="governance.consentrecord",
                        verbose_name="Consentimento LGPD",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_requests",
                        to="students.student",
                        verbose_name="Aluno (se já cadastrado)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Matrícula",
                "verbose_name_plural": "Solicitações de Matrícula",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriorityEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PCD", "Pessoa com Deficiência"),
                            ("SIBLING", "Irmão matriculado na unidade"),
                            (
                                "SOCIAL_VULNERABILITY",
                                "Vulnerabilidade social (CadÚnico)",
                            ),
                        ],
                        max_length=25,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="admissions/evidence/%Y/%m/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nome do arquivo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando verificação"),
                            ("VERIFIED", "Verificada"),
                            ("REJECTED", "Rejeitada"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verificado em"
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="Parecer")),
                (
                    "declared_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sibling_evidences",
                        to="schools.school",
                        verbose_name="Escola do irmão",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="admissions.enrollmentrequest",
                        verbose_name="Solicitação",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_evidences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante de Prioridade",
                "verbose_name_plural": "Comprovantes de Prioridade",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RenewalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("STAY", "Permanece na mesma escola"),
                            ("INTERNAL_TRANSFER", "Deseja transferência interna"),
                            ("NOT_RETURNING", "Não retorna à rede"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Decisão",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "residential_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço residencial"
                    ),
                ),
                (
                    "residential_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "residential_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "has_new_special_needs",
                    models.BooleanField(default=False, verbose_name="Novo laudo / NEE"),
                ),
                (
                    "special_needs_note",
                    models.TextField(blank=True, verbose_name="Observação NEE"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmado em"
                    ),
                ),
                (
                    "current_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renewal_requests",
                        to="students.enrollment",
                        verbose_name="Matrícula vigente",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_requests",
                        to="admissions.admissioncycle",
                        verbose_name="Ciclo",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewal_confirmations",
                        to="students.guardian",
                        verbose_name="Responsável que confirmou",
                    ),
                ),
                (
                    "next_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewed_from",
                        to="students.enrollment",
                        verbose_name="Matrícula do ano de destino",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_requests",
                        to="students.student",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rematrícula",
                "verbose_name_plural": "Rematrículas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="renewal_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_request",
                to="admissions.renewalrequest",
                verbose_name="Rematrícula de origem",
            ),
        ),
        migrations.CreateModel(
            name="SchoolPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        verbose_name="Ordem de preferência"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="admissions.enrollmentrequest",
                        verbose_name="Solicitação",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_preferences",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência de Escola",
                "verbose_name_plural": "Preferências de Escola",
                "ordering": ["rank"],
            },
        ),
        migrations.AddConstraint(
            model_name="admissioncycle",
            constraint=models.UniqueConstraint(
                fields=("education_department", "target_academic_year"),
                name="uq_admission_cycle_dept_year",
            ),
        ),
        migrations.AddIndex(
            model_name="priorityevidence",
            index=models.Index(
                fields=["status", "kind"], name="admissions__status_b40040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="renewalrequest",
            index=models.Index(
                fields=["cycle", "outcome"], name="admissions__cycle_i_00c9e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="renewalrequest",
            constraint=models.UniqueConstraint(
                fields=("cycle", "student"), name="uq_renewal_cycle_student"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentrequest",
            index=models.Index(
                fields=["cycle", "status"], name="admissions__cycle_i_b2c314_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student__isnull", False)),
                fields=("cycle", "student"),
                name="uq_request_cycle_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("applicant_cpf__isnull", False), ("student__isnull", True)
                ),
                fields=("cycle", "applicant_cpf"),
                name="uq_request_cycle_applicant_cpf",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolpreference",
            constraint=models.UniqueConstraint(
                fields=("request", "rank"), name="uq_preference_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolpreference",
            constraint=models.UniqueConstraint(
                fields=("request", "school"), name="uq_preference_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank__gte", 1), ("rank__lte", 3)),
                name="ck_preference_rank_1_3",
            ),
        ),
    ]
